#:schema https://mago.carthage.software/1.46.0/schema.json
version = "1"
php-version = "8.2.0"

[source]
workspace = "."
paths = ["src/", "tests/"]
includes = ["vendor"]
excludes = []

[source.glob]
literal-separator = true

[analyzer]
find-unused-definitions = true
find-unused-expressions = true
analyze-dead-code = true
memoize-properties = true
check-throws = false
check-missing-override = true
find-unused-parameters = true
strict-list-index-checks = true
strict-array-index-existence = true
allow-array-truthy-operand = false
no-boolean-literal-comparison = true
check-missing-type-hints = true
check-closure-missing-type-hints = true
check-arrow-function-missing-type-hints = true
trust-existence-checks = false
check-use-statements = true
